### FIXED FOR GITHUB PAGES ###

# GENERAL SITE SETTINGS
title: "Portfolio"
description: "City Design"
url: "https://portfolio.github.io"
baseurl: ""

# LANDING PAGE
username: "Amogh Samji"
typing_text: "Engineering Student | Developer | Creator"
email: ""   # add later

github_username: amoghsamji
codepen_username: ""
dev_username: ""
linkedin_username: ""
twitter_username: ""

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: "About Me"
about_me_description: "Write your description here."

# SKILLS SECTION
show_skills_card: true
skills_title: "Skills"

# TIMELINE SECTION
show_timeline_card: true
timeline_title: "Education & Experience"
cv_download_link: ""

# PROJECTS SECTION
show_projects_card: true
show_projects: true
projects_title: "Projects"
show_os_projects: true
os_projects_title: "Open Source Projects"

# CONTACT SECTION
show_contact_card: true
contact_title: "Contact"
contact_description: "Feel free to reach out!"

# GITHUB-METADATA
repository: amoghsamji/portfolio.github.io

projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects:

# GOOGLE-ANALYTICS
google-analytics:
  id: ""

### REQUIRED FOR GITHUB PAGES ###
plugins:
  - jekyll-github-metadata

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
    "yarn.lock",
  ]
